### ISSUE TITLE
its not working 

### ISSUE THREAD

**Issue by AlOo2002** [Rairye/ht-getter#1]
its not working 
![Untitled](https://user-images.githubusercontent.com/45318547/177076497-37e8cce1-779f-4220-99de-95d50bc14a7a.png)

**Comment by Rairye** [comment]
Thank you for your message.

Could you double check this for me? There appear to be no hash tags in source_text.

**Comment by AlOo2002** [comment]
thanks for your reply. it's not working again

**Comment by Rairye** [comment]
Hello.

I changed source_text in your example to "#dog" and both of the above functions work correctly.
